# Base H2
spring.datasource.url=jdbc:h2:mem:produitsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Creation des tables et chargement de data.sql
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# Affichage SQL et console H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Limite des produits
mes-configs.limitDeProduits=5